package com.deloitte.Test_Deloitte.exceptions;

public class UsernameAlreadyTaken extends Exception {

}
